import { Categories } from 'emoji-picker-react';

export const emojiCategories = [
  { category: Categories.CUSTOM, name: 'Century' },
  { category: Categories.SUGGESTED, name: 'Frequently Used' },
  { category: Categories.SMILEYS_PEOPLE, name: 'Smileys & People' },
  { category: Categories.ANIMALS_NATURE, name: 'Animals & Nature' },
  { category: Categories.FOOD_DRINK, name: 'Food & Drink' },
  { category: Categories.TRAVEL_PLACES, name: 'Travel & Places' },
  { category: Categories.ACTIVITIES, name: 'Activities' },
  { category: Categories.OBJECTS, name: 'Objects' },
  { category: Categories.SYMBOLS, name: 'Symbols' },
  { category: Categories.FLAGS, name: 'Flags' },
];

export const customEmojis = [
  { names: ['Big Grin', 'big grin'], imgUrl: '/emotes/a_(biggrin)_40.webp', id: '(biggrin)' },
  { names: ['Smile', 'smile'], imgUrl: '/emotes/a_(smile)_40.webp', id: '(smile)' },
  { names: ['evil', '6'], imgUrl: '/emotes/a_(6)_40.webp', id: '(6)' },
  { names: ['a', 'angel'], imgUrl: '/emotes/a_(a)_40.webp', id: '(a)' },
  { names: ['aghast'], imgUrl: '/emotes/a_(aghast)_40.webp', id: '(aghast)' },
  { names: ['annoyed'], imgUrl: '/emotes/a_(annoyed)_40.webp', id: '(annoyed)' },
  { names: ['applause'], imgUrl: '/emotes/a_(applause)_40.webp', id: '(applause)' },
  { names: ['ashamed'], imgUrl: '/emotes/a_(ashamed)_40.webp', id: '(ashamed)' },
  { names: ['astonished'], imgUrl: '/emotes/a_(astonished)_40.webp', id: '(astonished)' },
  { names: ['blk', 'blink'], imgUrl: '/emotes/a_(blk)_40.webp', id: '(blk)' },
  { names: ['blowkiss'], imgUrl: '/emotes/a_(blowkiss)_40.webp', id: '(blowkiss)' },
  { names: ['bowing'], imgUrl: '/emotes/a_(bowing)_40.webp', id: '(bowing)' },
  { names: ['candyeat'], imgUrl: '/emotes/a_(candyeat)_40.webp', id: '(candyeat)' },
  { names: ['cb'], imgUrl: '/emotes/a_(cb)_40.webp', id: '(cb)' },
  { names: ['cd'], imgUrl: '/emotes/a_(cd)_40.webp', id: '(cd)' },
  { names: ['chew'], imgUrl: '/emotes/a_(chew)_40.webp', id: '(chew)' },
  { names: ['chkl'], imgUrl: '/emotes/a_(chkl)_40.webp', id: '(chkl)' },
  { names: ['cloud'], imgUrl: '/emotes/a_(cloud)_40.webp', id: '(cloud)' },
  { names: ['confounded'], imgUrl: '/emotes/a_(confounded)_40.webp', id: '(counfounded)' },
  { names: ['confused'], imgUrl: '/emotes/a_(confused)_40.webp', id: '(confused)' },
  { names: ['cool'], imgUrl: '/emotes/a_(cool)_40.webp', id: '(cool)' },
  { names: ['crazy'], imgUrl: '/emotes/a_(crazy)_40.webp', id: '(crazy)' },
  { names: ['crs'], imgUrl: '/emotes/a_(crs)_40.webp', id: '(crs)' },
  { names: ['cry', 'cry2'], imgUrl: '/emotes/a_(cry2)_40.webp', id: '(cry2)' },
  { names: ['cute'], imgUrl: '/emotes/a_(cute)_40.webp', id: '(cute)' },
  { names: ['cyc'], imgUrl: '/emotes/a_(cyc)_40.webp', id: '(cyc)' },
  { names: ['d'], imgUrl: '/emotes/a_(d)_40.webp', id: '(d)' },
  { names: ['dab'], imgUrl: '/emotes/a_(dab)_40.webp', id: '(dab)' },
  { names: ['dead'], imgUrl: '/emotes/a_(dead)_40.webp', id: '(dead)' },
  { names: ['depressed'], imgUrl: '/emotes/a_(depressed)_40.webp', id: '(depressed)' },
  { names: ['dhat'], imgUrl: '/emotes/a_(dhat)_40.webp', id: '(dhat)' },
  { names: ['dream'], imgUrl: '/emotes/a_(dream)_40.webp', id: '(dream)' },
  { names: ['dull'], imgUrl: '/emotes/a_(dull)_40.webp', id: '(dull)' },
  { names: ['ecstatic'], imgUrl: '/emotes/a_(ecstatic)_40.webp', id: '(ecstatic)' },
  { names: ['eek'], imgUrl: '/emotes/a_(eek)_40.webp', id: '(eek)' },
  { names: ['emo'], imgUrl: '/emotes/a_(emo)_40.webp', id: '(emo)' },
  { names: ['evil'], imgUrl: '/emotes/a_(evil)_40.webp', id: '(evil)' },
  { names: ['eyes'], imgUrl: '/emotes/a_(eyes)_40.webp', id: '(eyes)' },
  { names: ['flip'], imgUrl: '/emotes/a_(flip)_40.webp', id: '(flip)' },
  { names: ['flustered'], imgUrl: '/emotes/a_(flustered)_40.webp', id: '(flustered)' },
  { names: ['folded'], imgUrl: '/emotes/a_(folded)_40.webp', id: '(folded)' },
  { names: ['frown'], imgUrl: '/emotes/a_(frown)_40.webp', id: '(frown)' },
  { names: ['fs'], imgUrl: '/emotes/a_(fs)_40.webp', id: '(fs)' },
  { names: ['furious'], imgUrl: '/emotes/a_(furious)_40.webp', id: '(furious)' },
  { names: ['goo'], imgUrl: '/emotes/a_(goo)_40.webp', id: '(goo)' },
  { names: ['grad'], imgUrl: '/emotes/a_(grad)_40.webp', id: '(grad)' },
  { names: ['halo'], imgUrl: '/emotes/a_(halo)_40.webp', id: '(halo)' },
  { names: ['hehe'], imgUrl: '/emotes/a_(hehe)_40.webp', id: '(hehe)' },
  { names: ['hello'], imgUrl: '/emotes/a_(hello)_40.webp', id: '(hello)' },
  { names: ['hmm'], imgUrl: '/emotes/a_(hmm)_40.webp', id: '(hmm)' },
  { names: ['hug'], imgUrl: '/emotes/a_(hug)_40.webp', id: '(hug)' },
  { names: ['hula'], imgUrl: '/emotes/a_(hula)_40.webp', id: '(hula)' },
  { names: ['ill'], imgUrl: '/emotes/a_(ill)_40.webp', id: '(ill)' },
  { names: ['mad'], imgUrl: '/emotes/a_(mad)_40.webp', id: '(mad)' },
  { names: ['nod'], imgUrl: '/emotes/a_(nod)_40.webp', id: '(nod)' },
  { names: ['omg'], imgUrl: '/emotes/a_(omg)_40.webp', id: '(omg)' },
  { names: ['ono'], imgUrl: '/emotes/a_(ono)_40.webp', id: '(ono)' },
  { names: ['shifty'], imgUrl: '/emotes/a_(shifty)_40.webp', id: '(shifty)' },
  { names: ['shock'], imgUrl: '/emotes/a_(shock)_40.webp', id: '(shock)' },
  { names: ['sleep'], imgUrl: '/emotes/a_(sleep)_40.webp', id: '(sleep)' },
  { names: ['sleepy'], imgUrl: '/emotes/a_(sleepy)_40.webp', id: '(sleepy)' },
  { names: ['smirk'], imgUrl: '/emotes/a_(smirk)_40.webp', id: '(smirk)' },
  { names: ['smirk2'], imgUrl: '/emotes/a_(smirk2)_40.webp', id: '(smirk2)' },
  { names: ['smug'], imgUrl: '/emotes/a_(smug)_40.webp', id: '(smug)' },
  { names: ['sob'], imgUrl: '/emotes/a_(sob)_40.webp', id: '(sob)' },
  { names: ['straw'], imgUrl: '/emotes/a_(straw)_40.webp', id: '(straw)' },
  { names: ['swear'], imgUrl: '/emotes/a_(swear)_40.webp', id: '(swear)' },
  { names: ['tipsy'], imgUrl: '/emotes/a_(tipsy)_40.webp', id: '(tipsy)' },
  { names: ['toj'], imgUrl: '/emotes/a_(toj)_40.webp', id: '(toj)' },
  { names: ['twitch'], imgUrl: '/emotes/a_(twitch)_40.webp', id: '(twitch)' },
  { names: ['um'], imgUrl: '/emotes/a_(um)_40.webp', id: '(um)' },
  { names: ['vampire'], imgUrl: '/emotes/a_(vampire)_40.webp', id: '(vampire)' },
  { names: ['wary'], imgUrl: '/emotes/a_(wary)_40.webp', id: '(wary)' },
  { names: ['wt'], imgUrl: '/emotes/a_(wt)_40.webp', id: '(wt)' },
  { names: ['yawn'], imgUrl: '/emotes/a_(yawn)_40.webp', id: '(yawn)' },
  { names: ['yum'], imgUrl: '/emotes/a_(yum)_40.webp', id: '(yum)' },
  { names: ['penguin'], imgUrl: '/emotes/a_(penguin)_40.webp', id: '(penguin)' },
];

export const emojiMap: Record<string, string> = {
  '(biggrin)': '/emotes/a_(biggrin)_40.webp',
  '(smile)': '/emotes/a_(smile)_40.webp',
  '(6)': '/emotes/a_(6)_40.webp',
  '(a)': '/emotes/a_(a)_40.webp',
  '(aghast)': '/emotes/a_(aghast)_40.webp',
  '(annoyed)': '/emotes/a_(annoyed)_40.webp',
  '(applause)': '/emotes/a_(applause)_40.webp',
  '(ashamed)': '/emotes/a_(ashamed)_40.webp',
  '(astonished)': '/emotes/a_(astonished)_40.webp',
  '(blk)': '/emotes/a_(blk)_40.webp',
  '(blowkiss)': '/emotes/a_(blowkiss)_40.webp',
  '(bowing)': '/emotes/a_(bowing)_40.webp',
  '(candyeat)': '/emotes/a_(candyeat)_40.webp',
  '(cb)': '/emotes/a_(cb)_40.webp',
  '(cd)': '/emotes/a_(cd)_40.webp',
  '(chew)': '/emotes/a_(chew)_40.webp',
  '(chkl)': '/emotes/a_(chkl)_40.webp',
  '(cloud)': '/emotes/a_(cloud)_40.webp',
  '(counfounded)': '/emotes/a_(confounded)_40.webp',
  '(confused)': '/emotes/a_(confused)_40.webp',
  '(cool)': '/emotes/a_(cool)_40.webp',
  '(crazy)': '/emotes/a_(crazy)_40.webp',
  '(crs)': '/emotes/a_(crs)_40.webp',
  '(cry2)': '/emotes/a_(cry2)_40.webp',
  '(cute)': '/emotes/a_(cute)_40.webp',
  '(cyc)': '/emotes/a_(cyc)_40.webp',
  '(d)': '/emotes/a_(d)_40.webp',
  '(dab)': '/emotes/a_(dab)_40.webp',
  '(dead)': '/emotes/a_(dead)_40.webp',
  '(depressed)': '/emotes/a_(depressed)_40.webp',
  '(dhat)': '/emotes/a_(dhat)_40.webp',
  '(dream)': '/emotes/a_(dream)_40.webp',
  '(dull)': '/emotes/a_(dull)_40.webp',
  '(ecstatic)': '/emotes/a_(ecstatic)_40.webp',
  '(eek)': '/emotes/a_(eek)_40.webp',
  '(emo)': '/emotes/a_(emo)_40.webp',
  '(evil)': '/emotes/a_(evil)_40.webp',
  '(eyes)': '/emotes/a_(eyes)_40.webp',
  '(flip)': '/emotes/a_(flip)_40.webp',
  '(flustered)': '/emotes/a_(flustered)_40.webp',
  '(folded)': '/emotes/a_(folded)_40.webp',
  '(frown)': '/emotes/a_(frown)_40.webp',
  '(fs)': '/emotes/a_(fs)_40.webp',
  '(furious)': '/emotes/a_(furious)_40.webp',
  '(goo)': '/emotes/a_(goo)_40.webp',
  '(grad)': '/emotes/a_(grad)_40.webp',
  '(halo)': '/emotes/a_(halo)_40.webp',
  '(hehe)': '/emotes/a_(hehe)_40.webp',
  '(hello)': '/emotes/a_(hello)_40.webp',
  '(hmm)': '/emotes/a_(hmm)_40.webp',
  '(hug)': '/emotes/a_(hug)_40.webp',
  '(hula)': '/emotes/a_(hula)_40.webp',
  '(ill)': '/emotes/a_(ill)_40.webp',
  '(mad)': '/emotes/a_(mad)_40.webp',
  '(nod)': '/emotes/a_(nod)_40.webp',
  '(omg)': '/emotes/a_(omg)_40.webp',
  '(ono)': '/emotes/a_(ono)_40.webp',
  '(shifty)': '/emotes/a_(shifty)_40.webp',
  '(shock)': '/emotes/a_(shock)_40.webp',
  '(sleep)': '/emotes/a_(sleep)_40.webp',
  '(sleepy)': '/emotes/a_(sleepy)_40.webp',
  '(smirk)': '/emotes/a_(smirk)_40.webp',
  '(smirk2)': '/emotes/a_(smirk2)_40.webp',
  '(smug)': '/emotes/a_(smug)_40.webp',
  '(sob)': '/emotes/a_(sob)_40.webp',
  '(straw)': '/emotes/a_(straw)_40.webp',
  '(swear)': '/emotes/a_(swear)_40.webp',
  '(tipsy)': '/emotes/a_(tipsy)_40.webp',
  '(toj)': '/emotes/a_(toj)_40.webp',
  '(twitch)': '/emotes/a_(twitch)_40.webp',
  '(um)': '/emotes/a_(um)_40.webp',
  '(vampire)': '/emotes/a_(vampire)_40.webp',
  '(wary)': '/emotes/a_(wary)_40.webp',
  '(wt)': '/emotes/a_(wt)_40.webp',
  '(yawn)': '/emotes/a_(yawn)_40.webp',
  '(yum)': '/emotes/a_(yum)_40.webp',
  '(penguin)': '/emotes/a_(penguin)_40.webp',
};
