import { Categories } from 'emoji-picker-react';

export const emojiCategories = [
  { category: Categories.CUSTOM, name: 'Century' },
  { category: Categories.SUGGESTED, name: 'Frequently Used' },
  { category: Categories.SMILEYS_PEOPLE, name: 'Smileys & People' },
  { category: Categories.ANIMALS_NATURE, name: 'Animals & Nature' },
  { category: Categories.FOOD_DRINK, name: 'Food & Drink' },
  { category: Categories.TRAVEL_PLACES, name: 'Travel & Places' },
  { category: Categories.ACTIVITIES, name: 'Activities' },
  { category: Categories.OBJECTS, name: 'Objects' },
  { category: Categories.SYMBOLS, name: 'Symbols' },
  { category: Categories.FLAGS, name: 'Flags' },
];

export const customEmojis = [
  { names: ['Big Grin', 'big grin'], imgUrl: '/emotes/a_(biggrin)_40.webp', id: '(biggrin)' },
  { names: ['Smile', 'smile'], imgUrl: '/emotes/a_(smile)_40.webp', id: '(smile)' },
  { names: ['evil', '6'], imgUrl: '/emotes/a_(6)_40.webp', id: '(6)' },
  { names: ['a', 'angel'], imgUrl: '/emotes/a_(a)_40.webp', id: '(a)' },
  { names: ['aghast'], imgUrl: '/emotes/a_(aghast)_40.webp', id: '(aghast)' },
  { names: ['annoyed'], imgUrl: '/emotes/a_(annoyed)_40.webp', id: '(annoyed)' },
  { names: ['applause'], imgUrl: '/emotes/a_(applause)_40.webp', id: '(applause)' },
  { names: ['ashamed'], imgUrl: '/emotes/a_(ashamed)_40.webp', id: '(ashamed)' },
  { names: ['astonished'], imgUrl: '/emotes/a_(astonished)_40.webp', id: '(astonished)' },
  { names: ['blk', 'blink'], imgUrl: '/emotes/a_(blk)_40.webp', id: '(blk)' },
  { names: ['blowkiss'], imgUrl: '/emotes/a_(blowkiss)_40.webp', id: '(blowkiss)' },
  { names: ['bowing'], imgUrl: '/emotes/a_(bowing)_40.webp', id: '(bowing)' },
  { names: ['candyeat'], imgUrl: '/emotes/a_(candyeat)_40.webp', id: '(candyeat)' },
  { names: ['cb'], imgUrl: '/emotes/a_(cb)_40.webp', id: '(cb)' },
  { names: ['cd'], imgUrl: '/emotes/a_(cd)_40.webp', id: '(cd)' },
  { names: ['chew'], imgUrl: '/emotes/a_(chew)_40.webp', id: '(chew)' },
  { names: ['chkl'], imgUrl: '/emotes/a_(chkl)_40.webp', id: '(chkl)' },
  { names: ['cloud'], imgUrl: '/emotes/a_(cloud)_40.webp', id: '(cloud)' },
  { names: ['confounded'], imgUrl: '/emotes/a_(confounded)_40.webp', id: '(counfounded)' },
  { names: ['confused'], imgUrl: '/emotes/a_(confused)_40.webp', id: '(confused)' },
  { names: ['cool'], imgUrl: '/emotes/a_(cool)_40.webp', id: '(cool)' },
  { names: ['crazy'], imgUrl: '/emotes/a_(crazy)_40.webp', id: '(crazy)' },
  { names: ['crs'], imgUrl: '/emotes/a_(crs)_40.webp', id: '(crs)' },
  { names: ['cry', 'cry2'], imgUrl: '/emotes/a_(cry2)_40.webp', id: '(cry2)' },
  { names: ['cute'], imgUrl: '/emotes/a_(cute)_40.webp', id: '(cute)' },
  { names: ['cyc'], imgUrl: '/emotes/a_(cyc)_40.webp', id: '(cyc)' },
  { names: ['d'], imgUrl: '/emotes/a_(d)_40.webp', id: '(d)' },
  { names: ['dab'], imgUrl: '/emotes/a_(dab)_40.webp', id: '(dab)' },
  { names: ['dead'], imgUrl: '/emotes/a_(dead)_40.webp', id: '(dead)' },
  { names: ['depressed'], imgUrl: '/emotes/a_(depressed)_40.webp', id: '(depressed)' },
  { names: ['dhat'], imgUrl: '/emotes/a_(dhat)_40.webp', id: '(dhat)' },
  { names: ['dream'], imgUrl: '/emotes/a_(dream)_40.webp', id: '(dream)' },
  { names: ['dull'], imgUrl: '/emotes/a_(dull)_40.webp', id: '(dull)' },
  { names: ['ecstatic'], imgUrl: '/emotes/a_(ecstatic)_40.webp', id: '(ecstatic)' },
  { names: ['eek'], imgUrl: '/emotes/a_(eek)_40.webp', id: '(eek)' },
  { names: ['emo'], imgUrl: '/emotes/a_(emo)_40.webp', id: '(emo)' },
  { names: ['evil'], imgUrl: '/emotes/a_(evil)_40.webp', id: '(evil)' },
  { names: ['eyes'], imgUrl: '/emotes/a_(eyes)_40.webp', id: '(eyes)' },
  { names: ['flip'], imgUrl: '/emotes/a_(flip)_40.webp', id: '(flip)' },
  { names: ['flustered'], imgUrl: '/emotes/a_(flustered)_40.webp', id: '(flustered)' },
  { names: ['folded'], imgUrl: '/emotes/a_(folded)_40.webp', id: '(folded)' },
  { names: ['frown'], imgUrl: '/emotes/a_(frown)_40.webp', id: '(frown)' },
  { names: ['fs'], imgUrl: '/emotes/a_(fs)_40.webp', id: '(fs)' },
  { names: ['furious'], imgUrl: '/emotes/a_(furious)_40.webp', id: '(furious)' },
  { names: ['goo'], imgUrl: '/emotes/a_(goo)_40.webp', id: '(goo)' },
  { names: ['grad'], imgUrl: '/emotes/a_(grad)_40.webp', id: '(grad)' },
  { names: ['halo'], imgUrl: '/emotes/a_(halo)_40.webp', id: '(halo)' },
  { names: ['hehe'], imgUrl: '/emotes/a_(hehe)_40.webp', id: '(hehe)' },
  { names: ['hello'], imgUrl: '/emotes/a_(hello)_40.webp', id: '(hello)' },
  { names: ['hmm'], imgUrl: '/emotes/a_(hmm)_40.webp', id: '(hmm)' },
  { names: ['hug'], imgUrl: '/emotes/a_(hug)_40.webp', id: '(hug)' },
  { names: ['hula'], imgUrl: '/emotes/a_(hula)_40.webp', id: '(hula)' },
  { names: ['ill'], imgUrl: '/emotes/a_(ill)_40.webp', id: '(ill)' },
  { names: ['mad'], imgUrl: '/emotes/a_(mad)_40.webp', id: '(mad)' },
  { names: ['nod'], imgUrl: '/emotes/a_(nod)_40.webp', id: '(nod)' },
  { names: ['omg'], imgUrl: '/emotes/a_(omg)_40.webp', id: '(omg)' },
  { names: ['ono'], imgUrl: '/emotes/a_(ono)_40.webp', id: '(ono)' },
  { names: ['shifty'], imgUrl: '/emotes/a_(shifty)_40.webp', id: '(shifty)' },
  { names: ['shock'], imgUrl: '/emotes/a_(shock)_40.webp', id: '(shock)' },
  { names: ['sleep'], imgUrl: '/emotes/a_(sleep)_40.webp', id: '(sleep)' },
  { names: ['sleepy'], imgUrl: '/emotes/a_(sleepy)_40.webp', id: '(sleepy)' },
  { names: ['smirk'], imgUrl: '/emotes/a_(smirk)_40.webp', id: '(smirk)' },
  { names: ['smirk2'], imgUrl: '/emotes/a_(smirk2)_40.webp', id: '(smirk2)' },
  { names: ['smug'], imgUrl: '/emotes/a_(smug)_40.webp', id: '(smug)' },
  { names: ['sob'], imgUrl: '/emotes/a_(sob)_40.webp', id: '(sob)' },
  { names: ['straw'], imgUrl: '/emotes/a_(straw)_40.webp', id: '(straw)' },
  { names: ['swear'], imgUrl: '/emotes/a_(swear)_40.webp', id: '(swear)' },
  { names: ['tipsy'], imgUrl: '/emotes/a_(tipsy)_40.webp', id: '(tipsy)' },
  { names: ['toj'], imgUrl: '/emotes/a_(toj)_40.webp', id: '(toj)' },
  { names: ['twitch'], imgUrl: '/emotes/a_(twitch)_40.webp', id: '(twitch)' },
  { names: ['um'], imgUrl: '/emotes/a_(um)_40.webp', id: '(um)' },
  { names: ['vampire'], imgUrl: '/emotes/a_(vampire)_40.webp', id: '(vampire)' },
  { names: ['wary'], imgUrl: '/emotes/a_(wary)_40.webp', id: '(wary)' },
  { names: ['wt'], imgUrl: '/emotes/a_(wt)_40.webp', id: '(wt)' },
  { names: ['yawn'], imgUrl: '/emotes/a_(yawn)_40.webp', id: '(yawn)' },
  { names: ['yum'], imgUrl: '/emotes/a_(yum)_40.webp', id: '(yum)' },
  { names: ['penguin'], imgUrl: '/emotes/a_(penguin)_40.webp', id: '(penguin)' },
];

export const emojiMap: Record<string, { src: string; width?: number; height?: number }> = {
  '(biggrin)': { src: '/emotes/a_(biggrin)_40.webp' },
  '(smile)': { src: '/emotes/a_(smile)_40.webp' },
  '(6)': { src: '/emotes/a_(6)_40.webp' },
  '(a)': { src: '/emotes/a_(a)_40.webp' },
  '(aghast)': { src: '/emotes/a_(aghast)_40.webp' },
  '(annoyed)': { src: '/emotes/a_(annoyed)_40.webp' },
  '(applause)': { src: '/emotes/a_(applause)_40.webp' },
  '(ashamed)': { src: '/emotes/a_(ashamed)_40.webp' },
  '(astonished)': { src: '/emotes/a_(astonished)_40.webp' },
  '(blk)': { src: '/emotes/a_(blk)_40.webp' },
  '(blowkiss)': { src: '/emotes/a_(blowkiss)_40.webp' },
  '(bowing)': { src: '/emotes/a_(bowing)_40.webp' },
  '(candyeat)': { src: '/emotes/a_(candyeat)_40.webp' },
  '(cb)': { src: '/emotes/a_(cb)_40.webp' },
  '(cd)': { src: '/emotes/a_(cd)_40.webp' },
  '(chew)': { src: '/emotes/a_(chew)_40.webp' },
  '(chkl)': { src: '/emotes/a_(chkl)_40.webp' },
  '(cloud)': { src: '/emotes/a_(cloud)_40.webp' },
  '(confounded)': { src: '/emotes/a_(confounded)_40.webp' },
  '(confused)': { src: '/emotes/a_(confused)_40.webp' },
  '(cool)': { src: '/emotes/a_(cool)_40.webp' },
  '(crazy)': { src: '/emotes/a_(crazy)_40.webp' },
  '(crs)': { src: '/emotes/a_(crs)_40.webp' },
  '(cry2)': { src: '/emotes/a_(cry2)_40.webp' },
  '(cute)': { src: '/emotes/a_(cute)_40.webp' },
  '(cyc)': { src: '/emotes/a_(cyc)_40.webp' },
  '(d)': { src: '/emotes/a_(d)_40.webp' },
  '(dab)': { src: '/emotes/a_(dab)_40.webp' },
  '(dead)': { src: '/emotes/a_(dead)_40.webp' },
  '(depressed)': { src: '/emotes/a_(depressed)_40.webp' },
  '(dhat)': { src: '/emotes/a_(dhat)_40.webp' },
  '(dream)': { src: '/emotes/a_(dream)_40.webp' },
  '(dull)': { src: '/emotes/a_(dull)_40.webp' },
  '(ecstatic)': { src: '/emotes/a_(ecstatic)_40.webp' },
  '(eek)': { src: '/emotes/a_(eek)_40.webp' },
  '(emo)': { src: '/emotes/a_(emo)_40.webp' },
  '(evil)': { src: '/emotes/a_(evil)_40.webp' },
  '(eyes)': { src: '/emotes/a_(eyes)_40.webp' },
  '(flip)': { src: '/emotes/a_(flip)_40.webp' },
  '(flustered)': { src: '/emotes/a_(flustered)_40.webp' },
  '(folded)': { src: '/emotes/a_(folded)_40.webp' },
  '(frown)': { src: '/emotes/a_(frown)_40.webp' },
  '(fs)': { src: '/emotes/a_(fs)_40.webp' },
  '(furious)': { src: '/emotes/a_(furious)_40.webp' },
  '(goo)': { src: '/emotes/a_(goo)_40.webp' },
  '(grad)': { src: '/emotes/a_(grad)_40.webp' },
  '(halo)': { src: '/emotes/a_(halo)_40.webp' },
  '(hehe)': { src: '/emotes/a_(hehe)_40.webp' },
  '(hello)': { src: '/emotes/a_(hello)_40.webp' },
  '(hmm)': { src: '/emotes/a_(hmm)_40.webp' },
  '(hug)': { src: '/emotes/a_(hug)_40.webp' },
  '(hula)': { src: '/emotes/a_(hula)_40.webp' },
  '(ill)': { src: '/emotes/a_(ill)_40.webp' },
  '(mad)': { src: '/emotes/a_(mad)_40.webp' },
  '(nod)': { src: '/emotes/a_(nod)_40.webp' },
  '(omg)': { src: '/emotes/a_(omg)_40.webp' },
  '(ono)': { src: '/emotes/a_(ono)_40.webp' },
  '(shifty)': { src: '/emotes/a_(shifty)_40.webp' },
  '(shock)': { src: '/emotes/a_(shock)_40.webp' },
  '(sleep)': { src: '/emotes/a_(sleep)_40.webp' },
  '(sleepy)': { src: '/emotes/a_(sleepy)_40.webp' },
  '(smirk)': { src: '/emotes/a_(smirk)_40.webp' },
  '(smirk2)': { src: '/emotes/a_(smirk2)_40.webp' },
  '(smug)': { src: '/emotes/a_(smug)_40.webp' },
  '(sob)': { src: '/emotes/a_(sob)_40.webp' },
  '(straw)': { src: '/emotes/a_(straw)_40.webp' },
  '(swear)': { src: '/emotes/a_(swear)_40.webp' },
  '(tipsy)': { src: '/emotes/a_(tipsy)_40.webp' },
  '(toj)': { src: '/emotes/a_(toj)_40.webp' },
  '(twitch)': { src: '/emotes/a_(twitch)_40.webp' },
  '(um)': { src: '/emotes/a_(um)_40.webp' },
  '(vampire)': { src: '/emotes/a_(vampire)_40.webp' },
  '(wary)': { src: '/emotes/a_(wary)_40.webp' },
  '(wt)': { src: '/emotes/a_(wt)_40.webp' },
  '(yawn)': { src: '/emotes/a_(yawn)_40.webp' },
  '(yum)': { src: '/emotes/a_(yum)_40.webp' },
  '(penguin)': { src: '/emotes/a_(penguin)_40.webp' },
  '(admin-icon)': { src: '/misc/owner.png', width: 15, height: 20 },
};
