import Image from 'next/image';
import { Flex } from '@mantine/core';

export default function Page() {
  return (
    <Flex gap="md" wrap="wrap">
      <Image src="/rotmg/Screenshot_100.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_103.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_104.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_111.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_112.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_113.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_114.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_115.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_116.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_117.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_118.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_119.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_120.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_121.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_122.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_123.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_124.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_125.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_126.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_127.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_128.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_129.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_130.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_131.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_132.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_133.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_134.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_135.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_136.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_137.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_138.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_139.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_140.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_141.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_142.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_143.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_144.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_145.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_146.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_147.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_148.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_149.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_150.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_151.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_152.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_153.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_154.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_155.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_156.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_157.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_158.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_159.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_160.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_161.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_162.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_163.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_164.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_165.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_166.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_167.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_168.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_169.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_170.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_171.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_172.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_173.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_174.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_175.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_176.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_177.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_178.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_179.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_180.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_181.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_182.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_183.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_184.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_185.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_186.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_187.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_188.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_189.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_190.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_191.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_192.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_193.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_194.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_195.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_196.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_197.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_198.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_199.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_200.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_201.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_202.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_203.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_204.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_205.png" width={600} height={480} alt="death screenshot" />
      <Image src="/rotmg/Screenshot_206.png" width={600} height={480} alt="death screenshot" />
    </Flex>
  );
}
