import Image from 'next/image';
import { Flex } from '@mantine/core';

export default function Page() {
  return (
    <Flex gap="md" wrap="wrap">
      <Image src="ROTMG/Screenshot_100.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_103.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_104.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_111.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_112.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_113.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_114.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_115.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_116.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_117.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_118.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_119.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_120.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_121.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_122.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_123.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_124.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_125.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_126.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_127.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_128.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_129.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_130.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_131.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_132.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_133.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_134.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_135.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_136.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_137.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_138.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_139.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_140.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_141.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_142.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_143.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_144.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_145.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_146.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_147.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_148.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_149.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_150.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_151.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_152.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_153.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_154.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_155.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_156.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_157.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_158.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_159.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_160.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_161.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_162.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_163.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_164.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_165.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_166.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_167.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_168.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_169.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_170.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_171.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_172.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_173.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_174.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_175.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_176.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_177.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_178.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_179.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_180.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_181.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_182.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_183.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_184.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_185.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_186.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_187.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_188.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_189.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_190.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_191.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_192.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_193.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_194.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_195.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_196.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_197.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_198.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_199.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_200.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_201.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_202.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_203.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_204.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_205.png" width={600} height={480} alt="death screenshot" />
      <Image src="ROTMG/Screenshot_206.png" width={600} height={480} alt="death screenshot" />
    </Flex>
  );
}
